/**
 * Generate `words.frequent` lists for the language profiles from a
 * register-matched frequency corpus (OpenSubtitles, via hermitdave/FrequencyWords)
 * and write them to `src/frequent.generated.ts`.
 *
 * Run:  pnpm --filter @movar/lang-detect gen:profiles
 *
 * Subtitle register ≈ the register of card/video titles, so common content
 * words rank in. Languages without OpenSubtitles coverage (e.g. Belarusian,
 * which 404s in this source) are omitted here and fall back to a hand-curated
 * list in `profiles.ts`.
 *
 * The output is committed; this script is only re-run to refresh the data.
 */
/* eslint-disable no-console -- CLI script: progress output is intended */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

interface Source {
  code: string;
  script: 'cyrillic' | 'latin';
}

const YEAR = 2018;
const TOP_N = 400;
const SOURCES: readonly Source[] = [
  { code: 'uk', script: 'cyrillic' },
  { code: 'ru', script: 'cyrillic' },
  { code: 'en', script: 'latin' },
];

const sourceUrl = (code: string): string =>
  `https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/${YEAR}/${code}/${code}_50k.txt`;

// Keep only real words in the language's script (length ≥ 2). Drops numbers,
// punctuation, and foreign-script tokens (brand names, transliterations).
const TOKEN_RE: Record<Source['script'], RegExp> = {
  cyrillic: /^\p{Script=Cyrillic}{2,}$/u,
  latin: /^[a-z]{2,}$/,
};

/** First TOP_N script-matching words from a `word count\n…` frequency list. */
// Parse loop in an uncovered build script — CRAP is inflated purely by zero coverage.
// fallow-ignore-next-line complexity
function extractTopWords(text: string, re: RegExp): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const line of text.split('\n')) {
    const word = line.split(' ', 1)[0]?.toLowerCase();
    if (!word || seen.has(word) || !re.test(word)) continue;
    seen.add(word);
    out.push(word);
    if (out.length >= TOP_N) break;
  }
  return out;
}

async function topWords(src: Source): Promise<string[]> {
  const res = await fetch(sourceUrl(src.code));
  if (!res.ok) throw new Error(`${src.code}: HTTP ${res.status}`);
  return extractTopWords(await res.text(), TOKEN_RE[src.script]);
}

const entries: [string, string[]][] = [];
for (const src of SOURCES) {
  const words = await topWords(src);
  console.log(`${src.code}: ${words.length} words`);
  entries.push([src.code, words]);
}

const body = entries.map(([code, words]) => `  ${code}: ${JSON.stringify(words)},`).join('\n');

const file = `// GENERATED by scripts/gen-word-profiles.mts — do not edit by hand.
// Source: hermitdave/FrequencyWords (OpenSubtitles ${YEAR}), top ${TOP_N}
// script-filtered words/language. Regenerate: pnpm --filter @movar/lang-detect gen:profiles
export const FREQUENT_GENERATED: Readonly<Record<string, readonly string[]>> = {
${body}
};
`;

const here = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(here, '..', 'src', 'frequent.generated.ts');
await writeFile(outPath, file, 'utf8');
console.log(`Wrote ${outPath}`);
