/*
 * Bundle the host app's brand fonts into `Shared (App)/Resources/fonts.css`.
 *
 * The Safari *host* app renders a hand-authored screen in a WKWebView under a
 * strict CSP, with no bundler and no network — so it can't `@import` the
 * `@fontsource` CSS the extension uses. To keep the host screen visually 1:1
 * with the extension (Manrope display/body + IBM Plex Mono for codes/meta),
 * we read the same `@fontsource` woff2 files the extension ships and inline
 * them as base64 `@font-face` rules into a single self-hosted stylesheet.
 *
 * Why base64 (data: URIs) rather than copying the woff2 files in: the Xcode
 * project references Resources as individual files, so one generated `.css`
 * needs exactly one project reference (mirroring `movar-app.js`) instead of
 * ~16 binary font references across both app targets. Main.html relaxes
 * `font-src` to `'self' data:` so the data URIs load under the CSP.
 *
 * Output is gitignored and regenerated, exactly like `movar-app.js`: every
 * `build:safari` path runs this before Xcode's copy phase, so the file the
 * project references always exists.
 *
 * Subsets + unicode-range are copied from `@fontsource`'s own per-subset CSS
 * so the browser still picks latin vs cyrillic per glyph; the latin subset
 * carries the ↑/↓/→ arrows the priority + chain UI uses.
 */
import { createRequire } from 'node:module';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const require = createRequire(import.meta.url);
const ROOT = path.resolve(import.meta.dirname, '..');
const OUT = path.join(ROOT, 'safari', 'Movar', 'Shared (App)', 'Resources', 'fonts.css');

// Subset coverage — verbatim from @fontsource's generated CSS (latin + cyrillic
// only; the UA+EN host UI needs no greek/vietnamese/latin-ext). Both families
// publish the same two ranges.
const UNICODE_RANGE = {
  latin:
    'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  cyrillic: 'U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116',
};

/** Each family: the @fontsource package, the woff2 filename prefix, and the
 *  weights we embed. Weights mirror the extension's globals.css imports so the
 *  host app has the same display/body/mono ladder available. */
const FAMILIES = [
  {
    cssFamily: 'Manrope',
    pkg: '@fontsource/manrope',
    filePrefix: 'manrope',
    weights: [400, 500, 600, 700, 800],
  },
  {
    cssFamily: 'IBM Plex Mono',
    pkg: '@fontsource/ibm-plex-mono',
    filePrefix: 'ibm-plex-mono',
    weights: [400, 500, 600],
  },
];

const SUBSETS = ['latin', 'cyrillic'] as const;

/** Resolve a @fontsource package's `files/` dir via its package.json so the
 *  path survives the pnpm store hash. */
function filesDir(pkg: string): string {
  return path.join(path.dirname(require.resolve(`${pkg}/package.json`)), 'files');
}

async function faceFor(
  cssFamily: string,
  dir: string,
  filePrefix: string,
  subset: (typeof SUBSETS)[number],
  weight: number,
): Promise<string> {
  const file = path.join(dir, `${filePrefix}-${subset}-${weight}-normal.woff2`);
  const base64 = (await readFile(file)).toString('base64');
  return [
    '@font-face {',
    `  font-family: '${cssFamily}';`,
    '  font-style: normal;',
    '  font-display: swap;',
    `  font-weight: ${weight};`,
    `  src: url(data:font/woff2;base64,${base64}) format('woff2');`,
    `  unicode-range: ${UNICODE_RANGE[subset]};`,
    '}',
  ].join('\n');
}

const blocks: string[] = [
  '/*',
  ' * GENERATED by scripts/build-app-fonts.mts — do not edit by hand.',
  ' * Brand fonts (Manrope + IBM Plex Mono, latin + cyrillic) inlined as base64',
  " * so the host app's WKWebView matches the extension's typography under its",
  ' * no-network CSP. Regenerated on every build:safari; gitignored.',
  ' */',
];

let faceCount = 0;
for (const { cssFamily, pkg, filePrefix, weights } of FAMILIES) {
  const dir = filesDir(pkg);
  for (const weight of weights) {
    for (const subset of SUBSETS) {
      blocks.push(await faceFor(cssFamily, dir, filePrefix, subset, weight));
      faceCount += 1;
    }
  }
}

await writeFile(OUT, blocks.join('\n\n') + '\n', 'utf8');

const kb = Math.round(Buffer.byteLength(blocks.join('\n\n'), 'utf8') / 1024);
process.stdout.write(
  `[movar:app-fonts] wrote ${path.relative(ROOT, OUT)} — ${faceCount} faces, ${kb} KB\n`,
);
