import { isGoogleHost } from '@movar/host-match';
import type { SiteModel, SiteRule } from '../types';

// Google SERP: a Cyrillic query like `яблуко` (or even `картина`, which
// is identical in UA & RU) routinely surfaces Russian-language results
// because Google has no language hint and falls back to the larger
// Russian corpus. Accept-Language alone doesn't constrain results —
// `lr=lang_<code>` does. `hl` aligns the interface so the picker,
// sidebar, related searches etc. also match. Path-gated to /search
// because /maps and /images interpret `lr` differently (Maps can
// outright break). Enforce-mode because the interface can be Ukrainian
// while results are Russian — page-language alone wouldn't trigger.
//
// Empty-SERP bug (fixed, see `stripParams` below): queries like "Реле
// напруги" appeared to return zero organic results once this rule
// appended `hl`/`lr`, and it looked like a classifier gap (Google not
// having tagged enough Ukrainian pages for a strict `lr` filter). Direct
// testing disproved that: `lr=lang_uk` alone returns ~1.4M results, and
// even the joined `lr=lang_uk|lang_en` this rule actually sends returns
// ~1M once Chrome's `gs_lcrp` is stripped. The real cause was `gs_lcrp` —
// an opaque per-omnibox-session context blob generated *before* this
// rewrite runs — surviving onto the rewritten URL and pinning Google's
// serving to a candidate set computed under the pre-rewrite
// (Russian-leaning) context, which then intersects with the `lr` filter
// down to zero.
// One rule covers every google.* ccTLD via the shared predicate — the SERP
// rewrite is identical across ccTLDs — so `match` is only a label here.
export const googleRule: SiteRule = {
  match: 'google',
  matchHost: isGoogleHost,
  enforce: true,
  strategy: {
    type: 'searchParams',
    onlyOnPath: '/search',
    onlyWhenParam: 'q',
    // `lr` pipe-joins every preferred language (`lang_uk|lang_en`) so a
    // user with `[uk, en]` priority sees results in either language —
    // English speakers with Ukrainian #1 otherwise lose every English
    // result. `hl` stays single-valued (interface = one language). The
    // `lang_` prefix is uniform, so it rides `prefix` rather than a values map.
    params: [{ name: 'hl' }, { name: 'lr', prefix: 'lang_', joinPreferences: true }],
    // `sei` and `gs_lcrp` are Google/Chrome's opaque session tokens. `sei`
    // carries prior-session locale bias forward; `gs_lcrp` is generated by
    // the omnibox before this rewrite runs and can pin serving to a
    // candidate set computed under the pre-rewrite language context — down
    // to zero organic results once `lr` filters that pinned set (confirmed
    // by direct testing: removing only `gs_lcrp` took one query from 0 to
    // ~1M results with `hl`/`lr` unchanged). Drop both on every rewrite so
    // each query is judged on its own signals.
    stripParams: ['sei', 'gs_lcrp'],
  },
};

export const googleModel: SiteModel = { chunk: 'models/google.js', matches: isGoogleHost };
