/**
 * Pure CSS renderers — one per token set. Each returns a self-contained
 * stylesheet (the raw `:root, :host` custom properties *and* the Tailwind v4
 * `@theme` wiring for that set), so a consumer imports exactly the sets it uses
 * and bundles nothing else. No filesystem, no Node: the file I/O lives in
 * `scripts/gen-theme-css.mts`.
 *
 * Scope is `:root, :host` in one rule: `:root` serves normal documents, `:host`
 * re-establishes the vars inside a shadow tree (the diagnostics panel, where
 * WXT's `all: initial` reset blocks `:root` inheritance) — so one file works for
 * both and there's no separate `.host.css` variant.
 */

import {
  breakpoints,
  color,
  colorDarkOverrides,
  fontFamily,
  fontSizeUi,
  forest,
  radius,
  shadow,
  shadowDarkOverrides,
  size,
  space,
} from './tokens';

const GENERATED_BANNER = `/*
 * @generated by scripts/gen-theme-css.mts from @movar/theme's src/tokens.ts.
 * DO NOT EDIT — this file is git-ignored; run \`pnpm gen:theme\` to (re)create it.
 */`;

/** One rule set serving both normal DOM (`:root`) and shadow DOM (`:host`). */
const SCOPE = ':root, :host';

type Vars = readonly (readonly [string, string])[];

/** Render `--name: value;` lines at a fixed indent. */
function declarations(vars: Vars, indent: string): string {
  return vars.map(([name, value]) => `${indent}--${name}: ${value};`).join('\n');
}

/** A raw-variable stylesheet: light values on `:root, :host`, plus a
 *  `prefers-color-scheme: dark` override block when `darkVars` is non-empty. */
function varsCss(lightVars: Vars, darkVars: Vars): string {
  const light = `${SCOPE} {\n${declarations(lightVars, '  ')}\n}`;
  if (darkVars.length === 0) return light;
  return `${light}\n\n@media (prefers-color-scheme: dark) {\n  ${SCOPE} {\n${declarations(
    darkVars,
    '    ',
  )}\n  }\n}`;
}

/* -------------------------------------------------------------------------- */
/* Color — semantic palette (light + dark) + Forest scale                     */
/* -------------------------------------------------------------------------- */

export function renderColorCss(): string {
  const raw = varsCss(Object.entries(color.light), Object.entries(colorDarkOverrides));
  const inline = Object.keys(color.light).map((name) => `  --color-${name}: var(--${name});`);
  const forestScale = Object.entries(forest).map(
    ([step, hex]) => `  --color-forest-${step}: ${hex};`,
  );
  return `${GENERATED_BANNER}

${raw}

/* Semantic tokens → utilities via \`@theme inline\` (read the live vars, flip
 * with prefers-color-scheme). The Forest scale is a static \`@theme\` set for
 * charts + edge-case shading. */
@theme inline {
${inline.join('\n')}
}

@theme {
${forestScale.join('\n')}
}
`;
}

/* -------------------------------------------------------------------------- */
/* Typography — UI type scale + font families                                 */
/* -------------------------------------------------------------------------- */

export function renderTypographyCss(): string {
  const raw = varsCss(
    Object.entries(fontSizeUi).map(([k, v]) => [`text-ui-${k}`, v] as const),
    [],
  );
  const inline = Object.keys(fontSizeUi).map((k) => `  --text-ui-${k}: var(--text-ui-${k});`);
  const fonts = [
    `  --font-sans: ${fontFamily.sans};`,
    `  --font-display: ${fontFamily.display};`,
    `  --font-mono: ${fontFamily.mono};`,
  ];
  return `${GENERATED_BANNER}

${raw}

/* The \`text-ui-*\` utilities read the live vars; the type faces are a static set. */
@theme inline {
${inline.join('\n')}
}

@theme {
${fonts.join('\n')}
}
`;
}

/* -------------------------------------------------------------------------- */
/* Shadow — elevation (light + dark)                                          */
/* -------------------------------------------------------------------------- */

export function renderShadowCss(): string {
  const raw = varsCss(
    Object.entries(shadow.light).map(([k, v]) => [`shadow-${k}`, v] as const),
    Object.entries(shadowDarkOverrides).map(([k, v]) => [`shadow-${k}`, v] as const),
  );
  const inline = Object.keys(shadow.light).map((k) => `  --shadow-${k}: var(--shadow-${k});`);
  return `${GENERATED_BANNER}

${raw}

@theme inline {
${inline.join('\n')}
}
`;
}

/* -------------------------------------------------------------------------- */
/* Layout families — opt-in; most map onto Tailwind's built-in scales         */
/* -------------------------------------------------------------------------- */

/** Spacing scale as `--space-*` custom properties, for hand-written CSS that
 *  wants the raw ladder (utilities already have `p-4` etc. from Tailwind). */
export function renderSpaceCss(): string {
  return `${GENERATED_BANNER}

${varsCss(
  Object.entries(space).map(([k, v]) => [`space-${k}`, v] as const),
  [],
)}
`;
}

/** The bespoke popup/options card radius (14px) as a `rounded-card` utility.
 *  The other radii use Tailwind's `rounded-md`/`lg`/`xl` directly. */
export function renderRadiusCss(): string {
  return `${GENERATED_BANNER}

@theme {
  --radius-card: ${radius.card};
}
`;
}

/** The named layout sizes that appear in CSS (currently just the content cap). */
export function renderSizeCss(): string {
  return `${GENERATED_BANNER}

${varsCss([['content-max', size.contentMax]], [])}
`;
}

/** The allowed breakpoints as a Tailwind `@theme` set. Values match Tailwind's
 *  built-in defaults, so importing this is only needed to be explicit. */
export function renderBreakpointCss(): string {
  const bp = Object.entries(breakpoints).map(([k, v]) => `  --breakpoint-${k}: ${v};`);
  return `${GENERATED_BANNER}

@theme {
${bp.join('\n')}
}
`;
}
