/**
 * Pure CSS renderers — one per token set. Each returns a self-contained
 * stylesheet (the raw `:root, :host` custom properties *and* the Tailwind v4
 * `@theme` wiring for that set), so a consumer imports exactly the sets it uses
 * and bundles nothing else. No filesystem, no Node: the file I/O lives in
 * `scripts/gen-theme-css.mts`.
 *
 * Scope is `:root, :host` in one rule: `:root` serves normal documents, `:host`
 * re-establishes the vars inside a shadow tree (the diagnostics panel, where
 * WXT's `all: initial` reset blocks `:root` inheritance) — so one file works for
 * both and there's no separate `.host.css` variant.
 */

import {
  breakpoints,
  color,
  colorDarkOverrides,
  duration,
  fontFamily,
  fontSizeUi,
  forest,
  glow,
  letterSpacing,
  lineHeight,
  radius,
  shadow,
  shadowDarkOverrides,
  size,
  space,
  typeRoles,
} from './tokens';

const GENERATED_BANNER = `/*
 * @generated by scripts/gen-theme-css.mts from @movar/theme's src/tokens.ts.
 * DO NOT EDIT — this file is git-ignored; run \`pnpm gen:theme\` to (re)create it.
 */`;

/** One rule set serving both normal DOM (`:root`) and shadow DOM (`:host`). */
const SCOPE = ':root, :host';

type Vars = readonly (readonly [string, string])[];

/** Render `--name: value;` lines at a fixed indent. */
function declarations(vars: Vars, indent: string): string {
  return vars.map(([name, value]) => `${indent}--${name}: ${value};`).join('\n');
}

/** A raw-variable stylesheet: light values on `:root, :host`, plus a
 *  `prefers-color-scheme: dark` override block when `darkVars` is non-empty. */
function varsCss(lightVars: Vars, darkVars: Vars): string {
  const light = `${SCOPE} {\n${declarations(lightVars, '  ')}\n}`;
  if (darkVars.length === 0) return light;
  return `${light}\n\n@media (prefers-color-scheme: dark) {\n  ${SCOPE} {\n${declarations(
    darkVars,
    '    ',
  )}\n  }\n}`;
}

/* -------------------------------------------------------------------------- */
/* Color — semantic palette (light + dark) + Forest scale                     */
/* -------------------------------------------------------------------------- */

export function renderColorCss(): string {
  const raw = varsCss(Object.entries(color.light), Object.entries(colorDarkOverrides));
  const inline = Object.keys(color.light).map((name) => `  --color-${name}: var(--${name});`);
  const forestScale = Object.entries(forest).map(
    ([step, hex]) => `  --color-forest-${step}: ${hex};`,
  );
  return `${GENERATED_BANNER}

${raw}

/* Semantic tokens → utilities via \`@theme inline\` (read the live vars, flip
 * with prefers-color-scheme). The Forest scale is a static \`@theme\` set for
 * charts + edge-case shading. */
@theme inline {
${inline.join('\n')}
}

@theme {
${forestScale.join('\n')}
}
`;
}

/* -------------------------------------------------------------------------- */
/* Typography — UI type scale + font families                                 */
/* -------------------------------------------------------------------------- */

export function renderTypographyCss(): string {
  // Raw `:root, :host` vars for every scale — emitted unconditionally so
  // hand-written CSS can reference them via `var(--tracking-display)` etc. An
  // `@theme` var that no *utility* references gets tree-shaken, which would
  // break the Safari host app's hand-written `letter-spacing: var(...)`.
  const raw = varsCss(
    [
      ...Object.entries(fontSizeUi).map(([k, v]) => [`text-ui-${k}`, v] as const),
      ...Object.entries(letterSpacing).map(([k, v]) => [`tracking-${k}`, v] as const),
      ...Object.entries(lineHeight).map(([k, v]) => [`leading-${k}`, v] as const),
    ],
    [],
  );
  // `@theme inline` turns each into a utility that reads the live var above.
  const inline = [
    ...Object.keys(fontSizeUi).map((k) => `  --text-ui-${k}: var(--text-ui-${k});`),
    ...Object.keys(letterSpacing).map((k) => `  --tracking-${k}: var(--tracking-${k});`),
    ...Object.keys(lineHeight).map((k) => `  --leading-${k}: var(--leading-${k});`),
  ];
  const fonts = [
    `  --font-sans: ${fontFamily.sans};`,
    `  --font-display: ${fontFamily.display};`,
    `  --font-mono: ${fontFamily.mono};`,
  ];
  return `${GENERATED_BANNER}

${raw}

/* The \`text-ui-*\` / \`tracking-*\` / \`leading-*\` utilities read the live vars
 * above (always emitted, so hand-written \`var()\` resolves too); the type faces
 * are a static set. Brand-named keys don't shadow Tailwind's built-in scales. */
@theme inline {
${inline.join('\n')}
}

@theme {
${fonts.join('\n')}
}
`;
}

/* -------------------------------------------------------------------------- */
/* Type roles — semantic `@utility type-*` classes                            */
/* -------------------------------------------------------------------------- */

/**
 * The semantic type roles (styleguide §2.1) as Tailwind v4 `@utility` classes —
 * `type-eyebrow`, `type-heading`, `type-body`, … Each bundles a role's full
 * shape (family · size · weight · tracking · leading · transform) so the combo
 * is defined once instead of retyped per call site. Color is intentionally
 * absent (it stays an explicit `text-*` utility at the call site).
 *
 * Every declared value is a `var(--…)` into `typography.css`'s vars, so
 * **`type.css` must be imported alongside `typography.css`** (and `color.css`
 * for the `text-*` the caller pairs with it). Unlike a raw `:root` sheet these
 * are on-demand utilities: Tailwind emits a `type-*` rule only where it scans
 * the literal class (`@movar/ui`'s `<Text>` maps variants to static literals so
 * the scanner sees each one — never a `type-${variant}` template).
 */
export function renderTypeCss(): string {
  const blocks = Object.entries(typeRoles).map(([role, decls]) => {
    const body = Object.entries(decls)
      .map(([prop, value]) => `  ${prop}: ${value};`)
      .join('\n');
    return `@utility type-${role} {\n${body}\n}`;
  });
  return `${GENERATED_BANNER}

${blocks.join('\n\n')}
`;
}

/* -------------------------------------------------------------------------- */
/* Shadow — elevation (light + dark)                                          */
/* -------------------------------------------------------------------------- */

export function renderShadowCss(): string {
  const raw = varsCss(
    Object.entries(shadow.light).map(([k, v]) => [`shadow-${k}`, v] as const),
    Object.entries(shadowDarkOverrides).map(([k, v]) => [`shadow-${k}`, v] as const),
  );
  const inline = Object.keys(shadow.light).map((k) => `  --shadow-${k}: var(--shadow-${k});`);
  return `${GENERATED_BANNER}

${raw}

@theme inline {
${inline.join('\n')}
}
`;
}

/* -------------------------------------------------------------------------- */
/* Motion — transition durations                                              */
/* -------------------------------------------------------------------------- */

/** Raw `--duration-*` vars (for `var()` and `duration-[var(--duration-base)]`).
 *  Easing stays a typed constant — see the note on `easing` in tokens.ts. Movar
 *  ships no keyframe animation: the design is static apart from the toggle /
 *  hover transitions composed from these durations (styleguide §7). */
export function renderMotionCss(): string {
  const durations = Object.entries(duration).map(([k, v]) => `  --duration-${k}: ${v};`);
  return `${GENERATED_BANNER}

:root, :host {
${durations.join('\n')}
}
`;
}

/* -------------------------------------------------------------------------- */
/* Glow — decorative marketing aurora                                         */
/* -------------------------------------------------------------------------- */

/** The hero aurora glows as raw `--glow-*` vars (emerald/teal). A deliberate,
 *  documented exception to "one accent"; marketing references them via `var()`. */
export function renderGlowCss(): string {
  const vars = Object.entries(glow).map(([k, v]) => `  --glow-${k}: ${v};`);
  return `${GENERATED_BANNER}

:root, :host {
${vars.join('\n')}
}
`;
}

/* -------------------------------------------------------------------------- */
/* Layout families — opt-in; most map onto Tailwind's built-in scales         */
/* -------------------------------------------------------------------------- */

/** Spacing scale as `--space-*` custom properties, for hand-written CSS that
 *  wants the raw ladder (utilities already have `p-4` etc. from Tailwind). */
export function renderSpaceCss(): string {
  return `${GENERATED_BANNER}

${varsCss(
  Object.entries(space).map(([k, v]) => [`space-${k}`, v] as const),
  [],
)}
`;
}

/** The bespoke popup/options card radius (14px) as a `rounded-card` utility.
 *  The other radii use Tailwind's `rounded-md`/`lg`/`xl` directly. */
export function renderRadiusCss(): string {
  return `${GENERATED_BANNER}

@theme {
  --radius-card: ${radius.card};
}
`;
}

/** The named layout sizes that appear in CSS (currently just the content cap). */
export function renderSizeCss(): string {
  return `${GENERATED_BANNER}

${varsCss([['content-max', size.contentMax]], [])}
`;
}

/** The allowed breakpoints as a Tailwind `@theme` set. Values match Tailwind's
 *  built-in defaults, so importing this is only needed to be explicit. */
export function renderBreakpointCss(): string {
  const bp = Object.entries(breakpoints).map(([k, v]) => `  --breakpoint-${k}: ${v};`);
  return `${GENERATED_BANNER}

@theme {
${bp.join('\n')}
}
`;
}
