/**
 * Pure CSS renderers — turn the typed tokens into the three stylesheets the
 * product consumes. No filesystem, no Node: these functions just return
 * strings, so they're trivially unit-testable and the actual file I/O lives in
 * `scripts/gen-theme-css.mts`.
 *
 *   renderTokensCss()  → `:root` custom properties (light) + a
 *                        `prefers-color-scheme: dark` override block.
 *   renderHostCss()    → the same variables scoped to `:host`, for shadow-DOM
 *                        consumers (the diagnostics panel) where `:root` can't
 *                        reach inside the tree.
 *   renderThemeCss()   → the Tailwind v4 `@theme` wiring that maps the raw
 *                        variables into utility classes (`bg-surface`,
 *                        `text-ink-strong`, `font-mono`, `shadow-lg`, …).
 */

import {
  breakpoints,
  color,
  colorDark,
  fontFamily,
  fontSizeUi,
  forest,
  radius,
  shadow,
  shadowDark,
  size,
  space,
} from './tokens';

const GENERATED_BANNER = `/*
 * @generated by scripts/gen-theme-css.mts from @movar/theme's src/tokens.ts.
 * DO NOT EDIT BY HAND — run \`pnpm gen:theme\` to regenerate; \`pnpm check:theme\`
 * fails if this file drifts from the typed source.
 */`;

type Vars = readonly (readonly [string, string])[];

/** Render `  --name: value;` lines at a fixed indent. */
function declarations(vars: Vars, indent: string): string {
  return vars.map(([name, value]) => `${indent}--${name}: ${value};`).join('\n');
}

/** The full light-theme variable set (colors, UI type scale, spacing, sizes,
 *  shadows) as `--name → value` pairs, in declaration order. */
function lightVars(): Vars {
  return [
    ...Object.entries(color.light),
    ...Object.entries(fontSizeUi).map(([k, v]) => [`text-ui-${k}`, v] as const),
    ...Object.entries(space).map(([k, v]) => [`space-${k}`, v] as const),
    ['content-max', size.contentMax],
    ...Object.entries(shadow.light).map(([k, v]) => [`shadow-${k}`, v] as const),
  ];
}

/** The dark-theme overrides — only the variables that actually change. */
function darkVars(): Vars {
  return [
    ...Object.entries(colorDark),
    ...Object.entries(shadowDark).map(([k, v]) => [`shadow-${k}`, v] as const),
  ];
}

/** Raw custom properties, scoped to `selector` (`:root` or `:host`). */
function renderVarsCss(selector: string): string {
  return `${GENERATED_BANNER}

${selector} {
${declarations(lightVars(), '  ')}
}

@media (prefers-color-scheme: dark) {
  ${selector} {
${declarations(darkVars(), '    ')}
  }
}
`;
}

/** Design tokens as `:root` custom properties (light + dark). The primary
 *  stylesheet — imported by every app before its `@theme` wiring. */
export function renderTokensCss(): string {
  return renderVarsCss(':root');
}

/** Design tokens scoped to `:host`, for shadow-DOM consumers where `:root`
 *  doesn't match (e.g. the diagnostics in-page panel). */
export function renderHostCss(): string {
  return renderVarsCss(':host');
}

/** The Tailwind v4 `@theme` wiring: semantic colors + shadows + UI type scale
 *  are mapped `inline` (they resolve through the live `var(--…)` so utilities
 *  flip with `prefers-color-scheme`); the static families (forest scale, type
 *  faces, breakpoints, the bespoke card radius) are plain `@theme` entries. */
export function renderThemeCss(): string {
  const inlineColors = Object.keys(color.light).map((name) => `  --color-${name}: var(--${name});`);
  const inlineShadows = Object.keys(shadow.light).map(
    (k) => `  --shadow-${k}: var(--shadow-${k});`,
  );
  const inlineTypeUi = Object.keys(fontSizeUi).map((k) => `  --text-ui-${k}: var(--text-ui-${k});`);

  const forestScale = Object.entries(forest).map(
    ([step, hex]) => `  --color-forest-${step}: ${hex};`,
  );
  const fonts = [
    `  --font-sans: ${fontFamily.sans};`,
    `  --font-display: ${fontFamily.display};`,
    `  --font-mono: ${fontFamily.mono};`,
  ];
  const bp = Object.entries(breakpoints).map(([k, v]) => `  --breakpoint-${k}: ${v};`);

  return `${GENERATED_BANNER}

/*
 * Semantic tokens → Tailwind utilities, via \`@theme inline\` so they read the
 * live CSS variables and respond to prefers-color-scheme. Requires the raw
 * variables (\`@movar/theme/tokens.css\` or \`tokens.host.css\`) to be imported
 * first.
 */
@theme inline {
${inlineColors.join('\n')}

${inlineShadows.join('\n')}

${inlineTypeUi.join('\n')}
}

/*
 * Static families — the full Forest scale (charts + edge-case shading), the
 * type faces, the allowed breakpoints, and the bespoke popup/options card
 * radius. Stone neutrals are left at Tailwind's defaults (they match the
 * design's stone steps).
 */
@theme {
${forestScale.join('\n')}

${fonts.join('\n')}

${bp.join('\n')}

  --radius-card: ${radius.card};
}
`;
}
