#!/usr/bin/env bash
#
# Regenerate the e2e visual baselines (`*-linux.png`) inside the pinned
# Playwright container, so the committed PNGs are byte-identical to what
# CI's `e2e-offline` job compares against — it runs in the SAME image.
#
# Why Docker: Playwright screenshots are platform-specific. Chromium's text
# anti-aliasing differs across OSes (and across font stacks on the same OS),
# so a baseline generated on a contributor's macOS/Windows host bakes that
# host's rendering into the PNG and fails on CI's Linux. The repo commits a
# single Linux baseline set; running the update inside
# `mcr.microsoft.com/playwright:<ver>` pins the OS + fonts + Chromium build
# to exactly CI's, so "green locally" means "green on CI".
#
# Usage:
#   pnpm e2e:baselines                    # regenerate every offline baseline
#   pnpm e2e:baselines popup              # scope to specs whose FILENAME matches
#   pnpm e2e:baselines:marketing          # regenerate the marketing-site set
#
# Scope with a positional filename substring, not `-- --grep`: the extra `--`
# nx inserts swallows the flag and Playwright reports "No tests found". Note the
# filter matches the spec's *path*, so it can't select one case inside a
# data-driven spec — `... marketing install` finds nothing, because the install
# baselines are generated by `marketing.visual.spec.ts`. Regenerate that whole
# set and review which PNGs actually changed.
#
# Both entry points run this same script inside the same pinned image; the
# `:marketing` one sets `E2E_BASELINE_TARGET` to the marketing config's Nx
# update target (which serves the built Astro site via `astro preview`). Each
# target's `dependsOn` builds what the suite needs first — extension + host-app
# + diagnostics harness for the offline suite, the marketing site for marketing.
#
# Requires Docker. This is the only supported way to refresh baselines —
# there is no CI job that does it for you. Do NOT run
# `pnpm --filter @movar/e2e test:update` directly on your host: it writes a
# baseline stamped with your OS's rendering, which CI does not use.
set -euo pipefail

# Keep in lockstep with `@playwright/test` in pnpm-lock.yaml AND the
# `container:` image in .github/workflows/ci.yml — all three must name the
# same Playwright release or local baselines drift from what CI compares
# against. (Hardening TODO: pin by @sha256 digest to match the repo's
# SHA-pinned `uses:` policy; a floating tag can be re-published.)
readonly PW_IMAGE="mcr.microsoft.com/playwright:v1.60.0-noble"

# CI's `e2e-offline` job runs on `ubuntu-latest` — linux/amd64. Chromium's
# text anti-aliasing differs by CPU architecture, so baselines MUST be
# generated for amd64 or they diverge from what CI compares against. Pin the
# platform explicitly: `mcr.microsoft.com/playwright` is a multi-arch image,
# so on an Apple Silicon (arm64) host Docker would otherwise run the arm64
# variant NATIVELY and silently write arm64 baselines that fail CI across the
# board. `linux/amd64` runs emulated there (needs Docker's Rosetta/qemu) but
# matches CI byte-for-byte. On a native-amd64 host it's a no-op.
readonly PW_PLATFORM="linux/amd64"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly REPO_ROOT

# Which Nx `*:update` target runs inside the container. Defaults to the offline
# suite; `pnpm e2e:baselines:marketing` sets E2E_BASELINE_TARGET to the marketing
# config's update target (which builds the site + serves it via `astro preview`).
readonly NX_TARGET="${E2E_BASELINE_TARGET:-e2e:test:update}"

if ! command -v docker >/dev/null 2>&1; then
  echo "error: docker is required to regenerate baselines deterministically." >&2
  echo "       install Docker Desktop (or a compatible engine) and retry." >&2
  exit 1
fi

echo "==> Regenerating Linux visual baselines in ${PW_IMAGE}"
echo "    nx target: ${NX_TARGET}"
echo "    forwarding to playwright: ${*:-<all baselines>}"

# A named volume persists the pnpm store across runs so a re-regen is fast.
# The repo is bind-mounted read-write so the freshly written `*-linux.png`
# files land straight back in the work tree. The Chromium build is baked
# into the pinned image — the same one CI's e2e-offline job runs — so there
# is no `playwright install` step and local output cannot diverge from CI's.
#
# `E2E_SLOW_HOST=1` widens the Playwright time budgets for this run only (see
# apps/e2e/playwright.budgets.ts). Emulated amd64 is slow enough that the
# tallest full-page captures cannot complete `toHaveScreenshot`'s
# two-identical-shots handshake inside CI's timeout — and a timed-out test
# under `--update-snapshots=all` writes NOTHING, silently leaving that baseline
# stale. Nothing is being asserted here, so there is no signal to preserve.
# `pnpm install` inside the container writes Linux-native binaries into the
# bind-mounted node_modules; we restore the host's afterward. The
# e2e:test:update Nx target carries `--update-snapshots=all`, which rewrites
# every baseline (including sub-tolerance diffs a bare `--update-snapshots`
# would skip).
# The container leaves amd64-Linux node_modules in the bind-mounted tree, so the
# host's native binaries have to be put back. `--config.confirmModulesPurge=false`
# auto-confirms pnpm's modules-dir purge — required when the host arch differs
# from the container's (e.g. an Apple Silicon host, where pnpm must replace the
# amd64 binaries and would otherwise block on a no-TTY confirmation prompt).
# `CI=1` alone no longer suffices: under pnpm 11 the container's install would
# silently SKIP the purge, leave the host's darwin-arm64 modules in place, and
# then die in `wxt prepare` on a missing `rolldown-binding.linux-x64-gnu.node`.
# Hence the same flag on both installs — and, since pnpm 11.3, an explicit
# `rm -rf node_modules` inside the container before its install: the flag
# auto-answers the purge prompt, but 11.3 stopped asking at all when the
# lockfile has not moved, so the same failure came back through the same door.
# On a native-amd64 Linux host this is a cheap no-op.
restore_host_modules() {
  echo "==> Restoring host node_modules (native binaries)"
  if ! (cd "${REPO_ROOT}" && CI=1 pnpm install --frozen-lockfile --config.confirmModulesPurge=false); then
    echo "warning: could not restore host node_modules automatically." >&2
    echo "         run 'pnpm install' yourself. On a native-Linux host the" >&2
    echo "         container writes root-owned files; if so, first run:" >&2
    echo "         sudo chown -R \"\$(id -u):\$(id -g)\" node_modules" >&2
  fi
}

# Armed BEFORE the container can touch node_modules, because the restore has to
# survive a failed run. Without the trap, `set -e` aborts on a non-zero docker
# exit and strands the host on Linux modules — and the next invocation of this
# very script then dies before it starts, since pnpm 11's pre-script dependency
# check runs its own `pnpm install` and aborts on the no-TTY purge prompt. A
# test failure inside the container is entirely expected (that is what you came
# to fix); being locked out of the tool that fixes it is not.
trap restore_host_modules EXIT

docker run --rm \
  --platform "${PW_PLATFORM}" \
  -v "${REPO_ROOT}:/work" \
  -v movar-pnpm-store:/pnpm-store \
  -w /work \
  -e CI=1 \
  -e NX_DAEMON=false \
  -e COREPACK_ENABLE_DOWNLOAD_PROMPT=0 \
  -e E2E_SLOW_HOST=1 \
  "${PW_IMAGE}" \
  bash -euo pipefail -c '
    target="$1"; shift
    corepack enable
    # Delete the bind-mounted modules dir outright rather than trusting pnpm to
    # purge it. The flag below only auto-answers the purge prompt; under pnpm
    # 11.3 the install decides the tree is already up to date (the lockfile has
    # not moved), never asks, and leaves the host darwin-arm64 binaries in
    # place — then wxt prepare dies on a missing
    # rolldown-binding.linux-x64-gnu.node, which is the very failure the flag
    # was added to prevent. The restore trap above puts the host tree back.
    rm -rf node_modules
    pnpm install --frozen-lockfile --store-dir /pnpm-store --config.confirmModulesPurge=false
    xvfb-run -a pnpm nx run "$target" -- "$@"
  ' movar-e2e-baselines "${NX_TARGET}" "$@"

# Happy path: disarm and restore in place, so the review hint below prints last
# rather than behind a few minutes of install output.
trap - EXIT
restore_host_modules

echo "==> Done. Review the regenerated baselines:"
echo "    git status --short 'apps/e2e/src/**/*.visual.spec.ts-snapshots/'"
