#!/usr/bin/env node
/**
 * Convert fallow's "Refactoring Targets" table into an agent-consumable queue.
 * Reads .metrics/fallow.md (regenerated by `pnpm metrics`), writes docs/REFACTORING-QUEUE.md.
 *
 * Writes only when the SUBSTANCE changes — see writeQueue(). `pnpm metrics` runs
 * on nearly every PR (this file was touched by all 30 of the last 30 commits on
 * main) but fallow's findings move far more rarely, so most of those diffs were
 * nothing but two advancing timestamps, which contributors then reverted by hand.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import nodePath from 'node:path';
import { fileURLToPath } from 'node:url';

interface RefactoringTarget {
  efficiency: number;
  category: string;
  effort: string;
  confidence: string;
  file: string;
  recommendation: string;
}

const repoRoot = nodePath.resolve(nodePath.dirname(fileURLToPath(import.meta.url)), '..');
const inputPath = nodePath.resolve(repoRoot, '.metrics/fallow.md');
const outputPath = nodePath.resolve(repoRoot, 'docs/REFACTORING-QUEUE.md');

// The two lines that change on every run regardless of what fallow found: the
// frontmatter `date:` and the `- Generated:` stamp lifted from fallow's snapshot
// filename. Everything else is a function of the findings alone.
const VOLATILE_LINES = /^(?:date: \d{4}-\d{2}-\d{2}|- Generated: .*)$/gm;

/**
 * Write the queue, but only if it differs from what is already on disk by more
 * than those timestamps — otherwise leave the file completely untouched so
 * `git status` stays clean.
 *
 * Comparing modulo the volatile lines is only meaningful because
 * docs/REFACTORING-QUEUE.md is in .prettierignore: prettier used to realign the
 * markdown tables this script emits, which the next run would un-align, an edit
 * war no content comparison could ever settle.
 */
function writeQueue(content: string, summary: string): void {
  mkdirSync(nodePath.dirname(outputPath), { recursive: true });
  const shown = outputPath.replace(`${repoRoot}/`, '');
  let existing: string | null = null;
  try {
    existing = readFileSync(outputPath, 'utf8');
  } catch {
    existing = null;
  }
  if (
    existing !== null &&
    existing.replace(VOLATILE_LINES, '') === content.replace(VOLATILE_LINES, '')
  ) {
    console.error(`[fallow-targets] Queue unchanged — left ${shown} alone (timestamps only).`);
    return;
  }
  writeFileSync(outputPath, content);
  console.error(`[fallow-targets] ${summary} → ${shown}`);
}

const md = readFileSync(inputPath, 'utf8');

const headerMatch = /^## Health Score: (\d+) \(([A-F])\)/m.exec(md);
const healthScore = headerMatch?.[1] ?? '?';
const healthGrade = headerMatch?.[2] ?? '?';

const snapshotMatch = /Saved vital signs snapshot to .*?(\d{4}-\d{2}-\d{2}T[\d-]+Z)/.exec(md);
const generated =
  snapshotMatch?.[1]?.replace(/^(\d{4}-\d{2}-\d{2})T(\d{2})-(\d{2})-(\d{2})Z$/, '$1T$2:$3:$4Z') ??
  new Date().toISOString();

const headerExec = /^### Refactoring Targets \((\d+)\)\s*$/m.exec(md);
if (!headerExec) {
  // No targets means fallow found nothing worth refactoring — write an empty
  // queue so downstream tooling has a consistent file to consume.
  writeQueue(
    `---\ntype: queue\nid: REFACTORING-QUEUE\nstatus: empty\ndate: ${new Date().toISOString().slice(0, 10)}\nsummary: No refactoring targets surfaced by fallow.\n---\n\n# Refactoring queue\n\n> Auto-generated by \`pnpm metrics\`. Health score: **${healthScore} (${healthGrade})**. No targets — codebase is below all complexity thresholds.\n`,
    'No targets found — codebase is clean. Wrote empty queue',
  );
  process.exit(0);
}
const totalTargets = headerExec[1] ?? '0';

const afterHeader = md.slice(headerExec.index + headerExec[0].length);
const sectionEnd = afterHeader.search(/^(##|---)\s*$/m);
const section = sectionEnd === -1 ? afterHeader : afterHeader.slice(0, sectionEnd);

const targets: RefactoringTarget[] = [];
const rowRe =
  /^\|\s*([\d.]+)\s*\|\s*([^|]+?)\s*\|\s*([^/]+)\s*\/\s*([^|]+?)\s*\|\s*`([^`]+)`\s*\|\s*(.+?)\s*\|\s*$/;
for (const line of section.split('\n')) {
  const m = rowRe.exec(line);
  if (!m) continue;
  const [, efficiency, category, effort, confidence, file, recommendation] = m;
  if (file === 'File') continue;
  if (
    efficiency === undefined ||
    category === undefined ||
    effort === undefined ||
    confidence === undefined ||
    file === undefined ||
    recommendation === undefined
  ) {
    continue;
  }
  targets.push({
    efficiency: Number.parseFloat(efficiency),
    category: category.trim(),
    effort: effort.trim(),
    confidence: confidence.trim(),
    file: file.replace(/%5B/gi, '[').replace(/%5D/gi, ']'),
    recommendation,
  });
}

if (targets.length === 0) {
  console.error("[fallow-targets] Found 'Refactoring Targets' header but couldn't parse any rows.");
  process.exit(1);
}

const categoryEmoji: Record<string, string> = {
  complexity: '🌀',
  'dead code': '💀',
  'circular dependency': '🔁',
  'high impact': '💥',
  'untested risk': '🧪',
};

const id = (i: number): string => `REFACTOR-${String(i + 1).padStart(3, '0')}`;

const acceptanceFor = (t: RefactoringTarget): string => {
  const lines: string[] = [];
  switch (t.category) {
    case 'dead code': {
      lines.push(
        '- All exports flagged as unused are removed (or re-justified by adding a real consumer).',
        '- `pnpm metrics:audit` reports no new findings on this file.',
      );
      break;
    }
    case 'complexity': {
      lines.push(
        '- Cognitive complexity of the named function drops below 30.',
        '- File LOC reduced (function split into helpers).',
        '- `pnpm metrics:audit` reports no new findings on this file.',
      );
      break;
    }
    case 'circular dependency': {
      lines.push(
        '- Import cycle involving this file is broken.',
        '- `fallow --only dead-code --format json` reports 0 circular deps containing this file.',
      );
      break;
    }
    case 'high impact': {
      lines.push(
        '- File is split into focused units (no single file > 200 LOC).',
        '- Existing consumers updated to import from the new units; nothing left unused.',
      );
      break;
    }
    default: {
      lines.push('- `pnpm metrics:audit` reports no new findings on this file.');
    }
  }
  lines.push('- `pnpm validate` is green.');
  return lines.join('\n');
};

const promptFor = (t: RefactoringTarget, tid: string): string =>
  [
    `Task ${tid}.`,
    '',
    `**Target file:** \`${t.file}\``,
    `**Issue:** ${t.recommendation}`,
    `**Category:** ${t.category} · **Effort:** ${t.effort} · **Confidence:** ${t.confidence} · **Efficiency:** ${String(t.efficiency)}`,
    '',
    'Constraints:',
    '- Do not commit; the orchestrator commits after verification.',
    '- Do not modify unrelated files; scope strictly to this target.',
    '- Match existing code style; do not introduce new dependencies without justification.',
    '',
    'Verification (must all pass before reporting done):',
    '1. `pnpm metrics:audit` — fallow audit on the working-tree diff; no new findings.',
    '2. `pnpm validate` — typecheck + lint + test workspace-wide.',
  ].join('\n');

const out: string[] = [
  '---',
  'type: queue',
  'id: REFACTORING-QUEUE',
  'status: live',
  `date: ${new Date().toISOString().slice(0, 10)}`,
  'summary: Auto-generated agent task queue from fallow refactoring targets.',
  '---',
  '',
  '# Refactoring queue',
  '',
  '> Auto-generated by `pnpm metrics` → `scripts/fallow-targets.mts`. Do not edit; edits will be overwritten on next run.',
  '',
  '- Source report: [.metrics/fallow.md](../.metrics/fallow.md)',
  `- Health score: **${healthScore} (${healthGrade})**`,
  `- Targets surfaced: **${totalTargets}** (parsed: ${String(targets.length)})`,
  `- Generated: ${generated}`,
  '',
  '## How to consume',
  '',
  'Each entry below is a self-contained agent task. To execute one:',
  '',
  '1. Pick the highest-efficiency task you can complete in one sitting.',
  '2. Hand the **Subagent prompt** block to a Claude subagent (model: haiku for `dead code`/`circular dependency` low-effort, sonnet for `complexity` medium, opus for `complexity` high).',
  '3. After the subagent reports done, run `pnpm metrics:audit` to verify no new findings, then `pnpm metrics` to refresh this queue.',
  '4. The audit verdict (pass/warn/fail) is the gate. Treat warn as needing attention but not blocking.',
  '',
  'To run a batch in parallel, use the `dispatch` skill with this file as input.',
  '',
  '---',
  '',
];

const buckets: Record<string, number> = {};
for (const t of targets) {
  buckets[t.category] = (buckets[t.category] ?? 0) + 1;
}
out.push(
  '## Summary by category',
  '',
  '| Category | Count | Typical effort |',
  '|:---------|------:|:---------------|',
);
for (const [cat, count] of Object.entries(buckets).toSorted((a, b) => b[1] - a[1])) {
  const efforts = targets.filter((t) => t.category === cat).map((t) => t.effort);
  const dist = (['low', 'medium', 'high'] as const)
    .map((e) => `${e}:${String(efforts.filter((x) => x === e).length)}`)
    .join(' / ');
  out.push(`| ${categoryEmoji[cat] ?? ''} ${cat} | ${String(count)} | ${dist} |`);
}
out.push('', '---', '', '## Tasks', '');

for (const [i, t] of targets.entries()) {
  const tid = id(i);
  const emoji = categoryEmoji[t.category] ?? '🔧';
  out.push(
    `### ${tid} · ${emoji} ${t.category} · ${t.effort} effort · efficiency ${String(t.efficiency)}`,
    '',
    `**File:** \`${t.file}\`  `,
    `**Action:** ${t.recommendation}  `,
    `**Confidence:** ${t.confidence}`,
    '',
    '**Acceptance:**',
    '',
    acceptanceFor(t),
    '',
    '<details><summary>Subagent prompt</summary>',
    '',
    '```',
    promptFor(t, tid),
    '```',
    '',
    '</details>',
    '',
  );
}

writeQueue(out.join('\n'), `Wrote ${String(targets.length)} tasks`);
