#!/usr/bin/env node
/**
 * Generate (or verify) the README "## Metrics" block.
 *
 *   pnpm gen:readme                              # rewrite the block from source + snapshot
 *   tsx scripts/gen-readme-metrics.mts --check   # exit 1 if the block would change OR a promise is broken
 *   tsx scripts/gen-readme-metrics.mts --refresh # refresh dynamic metrics from .metrics/ + coverage/, then rewrite
 *
 * The README's `## Metrics` section carries a generated block between
 * `<!-- METRICS:START … -->` / `<!-- METRICS:END -->` markers: a row with the
 * StandWithUkraine badge and the self-explanatory metric badges, then a list that
 * doubles as the legend (every metric, its value, and how it's computed). Metric
 * badges are static
 * shields.io URLs with the value baked into the URL — nothing phones home and no
 * data is uploaded, matching the project's network-silent stance (GitHub's camo
 * proxies the image; only the number, already public in this file, travels). A
 * list (not a table) keeps the block prettier-stable: prettier realigns table
 * columns, which would fight the `--check` drift guard.
 *
 * Three classes of metric:
 *   - STATIC — derived live from a committed source (wxt manifest permissions,
 *     LICENSE). Always recomputable, so the parity guard checks them tool-free
 *     in pre-commit / CI.
 *   - DYNAMIC — produced by a heavy tool whose output is gitignored (fallow's
 *     health score in `.metrics/fallow.*`; Vitest coverage under each project's
 *     `coverage/` dir; the built content.js size in `.metrics/content-bundle.json`,
 *     written by the extension's check:content-bundle guard).
 *     These are snapshotted into the committed `scripts/readme-metrics.snapshot.json`
 *     by `--refresh` (which `pnpm metrics` runs after the tools regenerate
 *     their reports) so the guard never has to run the tool. Render reads the snapshot.
 *   - PROMISES — marketing claims from movar.fyi (apps/marketing) verified against
 *     committed sources (LICENSE, the extension manifest + source, settings defaults).
 *     Each is checked live every build; `--check` fails if any promise is broken, so
 *     a change that quietly violates a public claim can't land. Tool-free.
 *
 * (Network-silence — "nothing leaves your browser" — is verified as a promise
 * below, rather than a standalone badge.)
 *
 * Wired into `pnpm check:readme` (→ `pnpm validate`, lefthook pre-commit, CI
 * verify) via `--check`. Fix a drift failure with `pnpm gen:readme`; refresh the
 * dynamic numbers with `pnpm metrics`.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const readmePath = resolve(repoRoot, 'README.md');
const snapshotPath = resolve(repoRoot, 'scripts/readme-metrics.snapshot.json');
const fallowMdPath = resolve(repoRoot, '.metrics/fallow.md');
const bundleJsonPath = resolve(repoRoot, '.metrics/content-bundle.json');

const METRICS_START =
  '<!-- METRICS:START — generated by `pnpm gen:readme`; do not edit by hand -->';
const METRICS_END = '<!-- METRICS:END -->';

const BADGES_START =
  '<!-- METRICS:BADGES:START — generated by `pnpm gen:readme`; do not edit by hand -->';
const BADGES_END = '<!-- METRICS:BADGES:END -->';
const STAND_WITH_UKRAINE_BADGE =
  '[![Stand With Ukraine](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/StandWithUkraine.svg)](https://stand-with-ukraine.pp.ua)';

interface Metric {
  label: string;
  message: string;
  color: string;
  /** Show as a shields badge (true) or only as a list/legend row (false). */
  badge: boolean;
  /** Legend text: what it measures and how it's computed. */
  description: string;
  /** Optional nested legend bullets (e.g. per-permission or per-promise rows). */
  items?: string[];
}

interface Snapshot {
  _comment?: string;
  health?: { score: number; grade: string };
  loc?: number;
  suppressions?: { eslint: number; fallow: number };
  /** Aggregate Vitest coverage across test-bearing projects, percent. */
  coverage?: { lines: number; branches: number };
  /** Built size of the always-on content.js, KB (from check:content-bundle). */
  bundle?: { contentKb: number };
}

/** A marketing claim from apps/marketing paired with the code invariant that
 *  backs it. `kept` is the live verdict; `detail` says what was checked. */
interface PromiseCheck {
  claim: string;
  /** Where in the marketing site the claim is made. */
  source: string;
  kept: boolean;
  detail: string;
}

// --- shields.io static-badge encoding ---------------------------------------
// Field separator is `-`, so a literal `-` becomes `--` and a literal `_`
// becomes `__`; a space is written as `_`. Parens are percent-encoded so they
// can't be mistaken for the end of a markdown image URL.
function encodeSegment(value: string): string {
  return encodeURIComponent(value.replace(/-/g, '--').replace(/_/g, '__').replace(/ /g, '_'))
    .replace(/\(/g, '%28')
    .replace(/\)/g, '%29');
}

function badgeUrl({ label, message, color }: Metric): string {
  return `https://img.shields.io/badge/${encodeSegment(label)}-${encodeSegment(message)}-${color}`;
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

// --- dynamic snapshot (committed; refreshed from gitignored fallow/coverage) -
function readSnapshot(): Snapshot {
  return JSON.parse(readFileSync(snapshotPath, 'utf8')) as Snapshot;
}

/**
 * Refresh the committed snapshot from whatever dynamic sources are present:
 * fallow's health score (`.metrics/fallow.md`), aggregate Vitest coverage
 * (each project's `coverage/coverage-summary.json`), and a live source scan for LOC +
 * inline-suppression counts. The two tool-produced inputs are optional — when
 * one is absent the previous snapshot value is kept and a warning is printed —
 * so coverage can be refreshed without re-running fallow, and vice versa.
 * `pnpm metrics` runs both tools first, so it always refreshes everything.
 */
function refreshSnapshot(): Snapshot {
  const snapshot = readSnapshot();

  let report: string | null = null;
  try {
    report = readFileSync(fallowMdPath, 'utf8');
  } catch {
    report = null;
  }
  if (report) {
    const match = /Health Score:\s*(\d+)\s*\(([A-Za-z][+-]?)\)/.exec(report);
    if (!match) {
      throw new Error(
        '[readme-metrics] could not parse "Health Score: N (G)" from .metrics/fallow.md.',
      );
    }
    snapshot.health = { score: Number(match[1]), grade: match[2] };
  } else {
    console.warn(
      '[readme-metrics] .metrics/fallow.md not found — keeping the existing health score. Run `pnpm metrics` to refresh it.',
    );
  }

  const stats = scanSourceStats();
  snapshot.loc = stats.loc;
  snapshot.suppressions = { eslint: stats.eslint, fallow: stats.fallow };

  const coverage = aggregateCoverage();
  if (coverage) {
    snapshot.coverage = coverage;
  } else {
    console.warn(
      '[readme-metrics] no coverage-summary.json found — keeping the existing coverage. Run `pnpm test:coverage` to refresh it.',
    );
  }

  const contentKb = readBundleSize();
  if (contentKb != null) {
    snapshot.bundle = { contentKb };
  } else {
    console.warn(
      '[readme-metrics] .metrics/content-bundle.json not found — keeping the existing content.js size. Run `pnpm metrics` (it runs check:content-bundle) to refresh it.',
    );
  }

  writeFileSync(snapshotPath, `${JSON.stringify(snapshot, null, 2)}\n`);
  return snapshot;
}

function gradeColor(grade: string): string {
  switch (grade[0]?.toUpperCase()) {
    case 'A':
      return 'brightgreen';
    case 'B':
      return 'green';
    case 'C':
      return 'yellow';
    case 'D':
      return 'orange';
    default:
      return 'red';
  }
}

function coverageColor(pct: number): string {
  if (pct >= 90) return 'brightgreen';
  if (pct >= 80) return 'green';
  if (pct >= 70) return 'yellowgreen';
  if (pct >= 60) return 'yellow';
  if (pct >= 50) return 'orange';
  return 'red';
}

// --- static collectors (committed sources only) -----------------------------
const BUILD_DIRS = new Set([
  'node_modules',
  '.output',
  'dist',
  '.nx',
  '.wxt',
  'coverage',
  '.turbo',
]);

/** Single pass over `apps/` + `packages/` TypeScript: total source lines (tests
 *  excluded) and inline-suppression counts (every file). Volatile, so the values
 *  are snapshotted by `--refresh` rather than recomputed by the guard. */
function scanSourceStats(): { loc: number; eslint: number; fallow: number } {
  let loc = 0;
  let eslint = 0;
  let fallow = 0;
  const isTest = (name: string): boolean => /\.(test|spec|test-utils)\.tsx?$/.test(name);
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        if (!BUILD_DIRS.has(entry.name)) walk(resolve(dir, entry.name));
      } else if (/\.tsx?$/.test(entry.name)) {
        const text = readFileSync(resolve(dir, entry.name), 'utf8');
        eslint += (text.match(/eslint-disable/g) ?? []).length;
        fallow += (text.match(/fallow-ignore/g) ?? []).length;
        if (!isTest(entry.name)) loc += text.split('\n').length;
      }
    }
  };
  for (const group of ['apps', 'packages'] as const) walk(resolve(repoRoot, group));
  return { loc, eslint, fallow };
}

/**
 * Sum every `<project>/coverage/coverage-summary.json` (Vitest's `json-summary`
 * reporter) into a single repo-wide percentage, weighted by line/branch counts
 * — the correct way to combine coverage across independent test runs (averaging
 * per-project percentages would over-weight tiny packages). Projects with no
 * tests emit an empty summary (`lines.total === 0`) and are skipped, so the
 * number reflects the test-bearing projects only. Returns null when no summary
 * exists yet (coverage hasn't been run).
 */
function aggregateCoverage(): { lines: number; branches: number } | null {
  let linesCovered = 0;
  let linesTotal = 0;
  let branchesCovered = 0;
  let branchesTotal = 0;
  for (const group of ['apps', 'packages'] as const) {
    for (const entry of readdirSync(resolve(repoRoot, group), { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const file = resolve(repoRoot, group, entry.name, 'coverage/coverage-summary.json');
      if (!existsSync(file)) continue;
      const total = (
        JSON.parse(readFileSync(file, 'utf8')) as {
          total?: {
            lines?: { covered: number; total: number };
            branches?: { covered: number; total: number };
          };
        }
      ).total;
      if (!total?.lines || !total.branches || total.lines.total === 0) continue;
      linesCovered += total.lines.covered;
      linesTotal += total.lines.total;
      branchesCovered += total.branches.covered;
      branchesTotal += total.branches.total;
    }
  }
  if (linesTotal === 0) return null;
  const pct = (covered: number, total: number): number => Math.round((covered / total) * 1000) / 10;
  return { lines: pct(linesCovered, linesTotal), branches: pct(branchesCovered, branchesTotal) };
}

/** Built content.js size in KB, emitted by the extension's `check:content-bundle`
 *  guard into `.metrics/content-bundle.json`. Null when the guard hasn't run this
 *  cycle (mirrors aggregateCoverage — `--refresh` then keeps the prior value). */
function readBundleSize(): number | null {
  if (!existsSync(bundleJsonPath)) return null;
  const { contentKb } = JSON.parse(readFileSync(bundleJsonPath, 'utf8')) as { contentKb?: number };
  return typeof contentKb === 'number' ? contentKb : null;
}

/**
 * Browser permissions the extension manifest requests, plus the one-line reason
 * each is needed (mirrors deployment-checklist.md § Permission justifications,
 * kept terse for the README). A permission with no entry here makes the build
 * fail loudly — adding one to the manifest must come with a justification.
 */
const PERMISSION_WHY: Record<string, string> = {
  storage:
    'persist your settings, pause state, and the local corrections log (preferences sync; state stays on-device)',
  declarativeNetRequest:
    'rewrite the outgoing `Accept-Language` request header to your preferred language order via one declarative rule — request and response bodies are never read',
  alarms: 'auto-resume Movar when a timed (1-hour) pause expires',
};
const HOST_PERMISSION_WHY =
  'run the language-correction content script on whatever site you are viewing — no page content or browsing history leaves the device';

function parseManifestPermissions(): { permissions: string[]; hostWide: boolean } {
  const config = readFileSync(resolve(repoRoot, 'apps/extension/wxt.config.ts'), 'utf8');
  // `\b` does not break inside `host_permissions` / `data_collection_permissions`
  // (the `_` is a word char), so this matches only the standalone array.
  const match = /\bpermissions:\s*\[([^\]]*)\]/.exec(config);
  if (!match) {
    throw new Error(
      '[readme-metrics] could not find `permissions: [...]` in apps/extension/wxt.config.ts — ' +
        'update parseManifestPermissions() if the manifest moved.',
    );
  }
  const permissions = match[1]
    .split(',')
    .map((item) => item.trim().replace(/^['"]|['"]$/g, ''))
    .filter(Boolean);
  const hostWide = /host_permissions:\s*\[[^\]]*<all_urls>/.test(config);
  return { permissions, hostWide };
}

/** Per-permission "which + why" legend rows. Throws if the manifest gains a
 *  permission with no documented justification. */
function permissionItems(): string[] {
  const { permissions, hostWide } = parseManifestPermissions();
  const items = permissions.map((name) => {
    const why = PERMISSION_WHY[name];
    if (!why) {
      throw new Error(
        `[readme-metrics] extension permission \`${name}\` has no justification — ` +
          'add one to PERMISSION_WHY in scripts/gen-readme-metrics.mts (and deployment-checklist.md).',
      );
    }
    return `\`${name}\` — ${why}`;
  });
  if (hostWide) items.push(`\`host_permissions: <all_urls>\` — ${HOST_PERMISSION_WHY}`);
  return items;
}

function readLicense(): string {
  const license = readFileSync(resolve(repoRoot, 'LICENSE'), 'utf8');
  const match = /^(\S+) License/m.exec(license);
  if (!match) throw new Error('[readme-metrics] could not read the SPDX id from LICENSE.');
  return match[1];
}

// --- promises (marketing claims verified against committed sources) ----------
// i18n.ts has no runtime imports, so it's safe to import standalone under tsx
// (the parity guard does the same). Reading the live strings ties each promise
// to the actual marketing copy and surfaces a restructure of that copy.
async function readMarketingEn(): Promise<Record<string, unknown>> {
  const i18nPath = resolve(repoRoot, 'apps/marketing/src/i18n.ts');
  const mod = (await import(pathToFileURL(i18nPath).href)) as {
    strings?: { en?: Record<string, unknown> };
  };
  if (!mod.strings?.en) {
    throw new Error('[readme-metrics] apps/marketing/src/i18n.ts did not export `strings.en`.');
  }
  return mod.strings.en;
}

const OSI_LICENSES = new Set([
  'MIT',
  'Apache-2.0',
  'BSD-2-Clause',
  'BSD-3-Clause',
  'ISC',
  'MPL-2.0',
]);

function verifyOpenSource(): PromiseCheck {
  let spdx = '';
  try {
    spdx = readLicense();
  } catch {
    spdx = '';
  }
  const kept = OSI_LICENSES.has(spdx);
  return {
    claim: 'Open source',
    source: 'hero badge + footer',
    kept,
    detail: kept
      ? `root LICENSE is ${spdx}, an OSI-approved open-source license`
      : `root LICENSE is missing or not an OSI license (read ${spdx || 'nothing'})`,
  };
}

/** Walk runtime extension source (no tests/preview/mocks) for any call that
 *  sends data off-device. Returns `file:line` strings for each hit. */
function scanForEgress(): string[] {
  const hits: string[] = [];
  const root = resolve(repoRoot, 'apps/extension/src');
  const egress =
    /\bfetch\s*\(|new\s+XMLHttpRequest|\bsendBeacon\s*\(|new\s+WebSocket|new\s+EventSource/;
  const skip = (name: string): boolean =>
    /\.(test|spec|stories)\.tsx?$/.test(name) || name === 'browser-mock.ts';
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = resolve(dir, entry.name);
      if (entry.isDirectory()) {
        if (entry.name !== 'preview' && entry.name !== 'test' && !BUILD_DIRS.has(entry.name)) {
          walk(full);
        }
      } else if (/\.tsx?$/.test(entry.name) && !skip(entry.name)) {
        readFileSync(full, 'utf8')
          .split('\n')
          .forEach((line, i) => {
            if (egress.test(line)) hits.push(`${full.slice(repoRoot.length + 1)}:${i + 1}`);
          });
      }
    }
  };
  walk(root);
  return hits;
}

function verifyNetworkSilent(): PromiseCheck {
  const reasons: string[] = [];

  const config = readFileSync(resolve(repoRoot, 'apps/extension/wxt.config.ts'), 'utf8');
  if (!/data_collection_permissions:\s*\{\s*required:\s*\[\s*'none'\s*\]/.test(config)) {
    reasons.push("manifest no longer declares data_collection_permissions required: ['none']");
  }

  const pkg = JSON.parse(
    readFileSync(resolve(repoRoot, 'apps/extension/package.json'), 'utf8'),
  ) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };
  const deps = Object.keys({ ...pkg.dependencies, ...pkg.devDependencies });
  const TELEMETRY = ['posthog', 'mixpanel', 'amplitude', '@sentry', 'segment', 'analytics', 'gtag'];
  const tracking = deps.filter((d) => TELEMETRY.some((t) => d.toLowerCase().includes(t)));
  if (tracking.length)
    reasons.push(`tracking/analytics dependency present: ${tracking.join(', ')}`);

  const egress = scanForEgress();
  if (egress.length) {
    reasons.push(
      `network-egress call(s) in extension source: ${egress.slice(0, 3).join(', ')}${egress.length > 3 ? ', …' : ''}`,
    );
  }

  const kept = reasons.length === 0;
  return {
    claim: 'Nothing leaves your browser',
    source: 'hero badge + privacy section + limitations',
    kept,
    detail: kept
      ? "manifest declares data collection 'none', no analytics dependency, and no fetch/XHR/WebSocket/sendBeacon in the extension runtime"
      : reasons.join('; '),
  };
}

async function verifyContentFilterOff(): Promise<PromiseCheck> {
  const settingsPath = resolve(repoRoot, 'packages/settings/src/index.ts');
  const mod = (await import(pathToFileURL(settingsPath).href)) as {
    defaultSettings?: { contentModification?: boolean };
  };
  const off = mod.defaultSettings?.contentModification === false;
  return {
    claim: 'On-page filtering stays off until you turn it on',
    source: 'how-it-works step 2 + limitations',
    kept: off,
    detail: off
      ? '`defaultSettings.contentModification` is false in @movar/settings — DOM filtering ships opt-in'
      : '`defaultSettings.contentModification` is not false — on-page filtering would be on by default',
  };
}

/**
 * The marketing promises Movar makes, each verified against the code. Reading
 * the live marketing strings first anchors the list to apps/marketing: if that
 * copy is restructured so a promised claim disappears, this throws rather than
 * silently checking a promise the site no longer makes.
 */
async function collectPromises(): Promise<PromiseCheck[]> {
  const en = await readMarketingEn();
  const hero = en['hero'] as { badge?: { privacy?: string; openSource?: string } } | undefined;
  const limitations = en['limitations'] as { items?: unknown[] } | undefined;
  const howItWorks = en['howItWorks'] as { steps?: { note?: string }[] } | undefined;
  if (
    !hero?.badge?.privacy ||
    !hero.badge.openSource ||
    !Array.isArray(limitations?.items) ||
    limitations.items.length === 0 ||
    !howItWorks?.steps?.[1]?.note
  ) {
    throw new Error(
      '[readme-metrics] expected marketing promise anchors are missing from apps/marketing/src/i18n.ts ' +
        '(hero.badge.privacy/openSource, limitations.items, howItWorks.steps[1].note) — ' +
        'update collectPromises() if the marketing copy was restructured.',
    );
  }
  return [verifyOpenSource(), verifyNetworkSilent(), await verifyContentFilterOff()];
}

// --- assemble ----------------------------------------------------------------
function collectMetrics(snapshot: Snapshot, promises: PromiseCheck[]): Metric[] {
  const metrics: Metric[] = [];
  if (snapshot.health) {
    const { score, grade } = snapshot.health;
    metrics.push({
      label: 'code health',
      message: `${score} (${grade})`,
      color: gradeColor(grade),
      badge: true,
      description:
        'fallow maintainability score, 0-100 with an A-F grade, over complexity, ' +
        'duplication, dead code, and churn; refreshed by `pnpm metrics`.',
    });
  }
  if (snapshot.coverage) {
    const { lines, branches } = snapshot.coverage;
    metrics.push({
      label: 'coverage',
      message: `${Math.round(lines)}% lines · ${Math.round(branches)}% branches`,
      color: coverageColor(Math.min(lines, branches)),
      badge: true,
      description:
        'Vitest (v8) line and branch coverage, aggregated across the test-bearing ' +
        'workspace projects weighted by size; snapshotted by `pnpm metrics`.',
    });
  }
  if (snapshot.bundle) {
    metrics.push({
      label: 'content.js',
      message: `${snapshot.bundle.contentKb} KB`,
      color: 'blue',
      badge: true,
      description:
        'minified size of the always-on content script, injected into every page — ' +
        'franc and the language profiles live in the background worker, not here; ' +
        'held under budget by `check:content-bundle` and snapshotted by `pnpm metrics`.',
    });
  }
  metrics.push({
    label: 'license',
    message: readLicense(),
    color: 'green',
    badge: true,
    description: 'SPDX identifier read from the root `LICENSE` file.',
  });
  const kept = promises.filter((p) => p.kept).length;
  metrics.push({
    label: 'promises',
    message: `${kept}/${promises.length} kept`,
    color: kept === promises.length ? 'brightgreen' : 'red',
    badge: true,
    description:
      'public claims from movar.fyi (apps/marketing) verified against the code each ' +
      'build — `pnpm check:readme` fails if any breaks:',
    items: promises.map(
      (p) => `${p.kept ? '✓' : '✗'} **${p.claim}** — ${p.detail} _(marketing: ${p.source})_`,
    ),
  });
  metrics.push({
    label: 'permissions',
    message: `${parseManifestPermissions().permissions.length} requested`,
    color: 'blue',
    badge: false,
    description: 'browser permissions the extension manifest requests, each scoped to one job:',
    items: permissionItems(),
  });
  if (snapshot.loc != null) {
    metrics.push({
      label: 'lines of code',
      message: `${(snapshot.loc / 1000).toFixed(1)}k`,
      color: 'blue',
      badge: false,
      description:
        'TypeScript under `apps/` + `packages/`, tests excluded; snapshotted by `pnpm metrics`.',
    });
  }
  if (snapshot.suppressions) {
    const { eslint, fallow } = snapshot.suppressions;
    metrics.push({
      label: 'suppressions',
      message: `${eslint} eslint-disable · ${fallow} fallow-ignore`,
      color: 'blue',
      badge: false,
      description:
        'inline lint / complexity opt-outs across the tree; the fallow-ignore set is ' +
        'budgeted and each is justified at the call site.',
    });
  }
  return metrics;
}

// --- render + splice --------------------------------------------------------
// Top-of-README badge row + a link down to the full report in the `## Metrics`
// section.
function renderBadgeRow(metrics: Metric[]): string {
  const metricBadges = metrics
    .filter((m) => m.badge)
    .map((m) => `![${m.label}: ${m.message}](${badgeUrl(m)})`)
    .join('\n');
  const badges = `${STAND_WITH_UKRAINE_BADGE}\n${metricBadges}`;
  return `${BADGES_START}\n\n${badges}\n\n**[See the full metrics report →](#metrics)**\n\n${BADGES_END}`;
}

// The `## Metrics` section: the full legend — every metric, its value, how it's
// computed, and (for permissions / promises) a nested breakdown.
function renderReport(metrics: Metric[]): string {
  const legend = metrics
    .map((m) => {
      const head = `- **${capitalize(m.label)}** \`${m.message}\` — ${m.description}`;
      if (!m.items?.length) return head;
      return `${head}\n${m.items.map((item) => `  - ${item}`).join('\n')}`;
    })
    .join('\n');
  const note =
    '<sub>Generated by `pnpm gen:readme` from committed sources; the code-health ' +
    'score and coverage are snapshotted by `pnpm metrics`. The top README badge row ' +
    'includes the StandWithUkraine badge plus the self-explanatory metrics; this list ' +
    'is the full metrics legend.</sub>';
  return `${METRICS_START}\n\n${legend}\n\n${note}\n\n${METRICS_END}`;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function spliceRegion(readme: string, start: string, end: string, block: string): string {
  if (!readme.includes(start) || !readme.includes(end)) {
    throw new Error(
      `[readme-metrics] markers not found in README.md — restore the ${start} / ${end} pair.`,
    );
  }
  const existing = new RegExp(`${escapeRegExp(start)}[\\s\\S]*?${escapeRegExp(end)}`);
  return readme.replace(existing, block);
}

// --- main -------------------------------------------------------------------
const mode = process.argv.includes('--refresh')
  ? 'refresh'
  : process.argv.includes('--check')
    ? 'check'
    : 'write';

const snapshot = mode === 'refresh' ? refreshSnapshot() : readSnapshot();
const promises = await collectPromises();
const metrics = collectMetrics(snapshot, promises);
const readme = readFileSync(readmePath, 'utf8');
let next = spliceRegion(readme, BADGES_START, BADGES_END, renderBadgeRow(metrics));
next = spliceRegion(next, METRICS_START, METRICS_END, renderReport(metrics));
const refreshed = mode === 'refresh' ? ' (snapshot refreshed)' : '';
const broken = promises.filter((p) => !p.kept);

if (mode === 'check') {
  // Broken promises first: a broken promise also makes the block "stale", but the
  // actionable failure is the broken invariant, not "run gen:readme".
  if (broken.length) {
    console.error(
      '✗ Broken product promise(s) — the code no longer upholds a claim made on movar.fyi:',
    );
    for (const p of broken) console.error(`  ✗ ${p.claim}: ${p.detail}`);
    console.error(
      'Restore the invariant, or update the promise/marketing copy if the product genuinely changed.',
    );
    process.exit(1);
  }
  if (next !== readme) {
    console.error('✗ README metrics block is stale. Run `pnpm gen:readme` and commit README.md.');
    process.exit(1);
  }
  console.log('✓ README metrics block is up to date and all product promises hold.');
} else if (next !== readme) {
  writeFileSync(readmePath, next);
  if (broken.length) {
    console.warn(
      `⚠ ${broken.length} product promise(s) broken — \`pnpm check:readme\` will fail until fixed.`,
    );
  }
  console.log(`✓ Wrote README metrics block${refreshed}.`);
} else {
  if (broken.length) {
    console.warn(
      `⚠ ${broken.length} product promise(s) broken — \`pnpm check:readme\` will fail until fixed.`,
    );
  }
  console.log(`✓ README metrics block already current${refreshed}.`);
}
