#!/usr/bin/env node
/**
 * Generate (or verify) the README metrics badge block.
 *
 *   pnpm gen:readme                              # rewrite the block from source + snapshot
 *   tsx scripts/gen-readme-metrics.mts --check   # exit 1 if the block would change
 *   tsx scripts/gen-readme-metrics.mts --refresh # refresh dynamic metrics from .metrics/, then rewrite
 *
 * The root README carries a small, generated badge row between
 * `<!-- METRICS:START … -->` / `<!-- METRICS:END -->` markers. Badges are static
 * shields.io URLs with the value baked into the URL: nothing phones home and no
 * data is uploaded, matching the project's network-silent stance (GitHub's camo
 * proxies the image; only the number — already public in this file — travels).
 *
 * Two classes of metric:
 *   - STATIC — derived live from a committed source (site-rules DB, wxt manifest
 *     permissions, test files, workspace members, LICENSE). Always recomputable,
 *     so the parity guard checks them tool-free in pre-commit / CI.
 *   - DYNAMIC — produced by a heavy tool whose output is gitignored (fallow's
 *     health score in `.metrics/fallow.*`; later: coverage %, bundle size). These
 *     are snapshotted into the committed `scripts/readme-metrics.snapshot.json`
 *     by `--refresh` (which `pnpm metrics` runs after fallow regenerates its
 *     reports) so the guard never has to run the tool. Render reads the snapshot.
 *
 * Still to wire (each needs its own tool + a snapshot field): coverage %,
 * content.js bundle size, the verified "sends nothing" network-silence badge.
 *
 * Wired into `pnpm check:readme` (→ `pnpm validate`, lefthook pre-commit, CI
 * verify) via `--check`. Fix a drift failure with `pnpm gen:readme`; refresh the
 * dynamic numbers with `pnpm metrics`.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const readmePath = resolve(repoRoot, 'README.md');
const snapshotPath = resolve(repoRoot, 'scripts/readme-metrics.snapshot.json');
const fallowMdPath = resolve(repoRoot, '.metrics/fallow.md');

const METRICS_START =
  '<!-- METRICS:START — generated by `pnpm gen:readme`; do not edit by hand -->';
const METRICS_END = '<!-- METRICS:END -->';

interface Metric {
  label: string;
  message: string;
  color: string;
}

interface Snapshot {
  _comment?: string;
  health?: { score: number; grade: string };
}

// --- shields.io static-badge encoding ---------------------------------------
// Field separator is `-`, so a literal `-` becomes `--` and a literal `_`
// becomes `__`; a space is written as `_`. Parens are percent-encoded so they
// can't be mistaken for the end of a markdown image URL.
function encodeSegment(value: string): string {
  return encodeURIComponent(value.replace(/-/g, '--').replace(/_/g, '__').replace(/ /g, '_'))
    .replace(/\(/g, '%28')
    .replace(/\)/g, '%29');
}

function badgeUrl({ label, message, color }: Metric): string {
  return `https://img.shields.io/badge/${encodeSegment(label)}-${encodeSegment(message)}-${color}`;
}

// --- dynamic snapshot (committed; refreshed from gitignored fallow output) ---
function readSnapshot(): Snapshot {
  return JSON.parse(readFileSync(snapshotPath, 'utf8')) as Snapshot;
}

function refreshSnapshot(): Snapshot {
  let report: string;
  try {
    report = readFileSync(fallowMdPath, 'utf8');
  } catch {
    throw new Error(
      '[readme-metrics] .metrics/fallow.md not found — run `pnpm metrics` before `--refresh`.',
    );
  }
  const match = /Health Score:\s*(\d+)\s*\(([A-Za-z][+-]?)\)/.exec(report);
  if (!match) {
    throw new Error(
      '[readme-metrics] could not parse "Health Score: N (G)" from .metrics/fallow.md.',
    );
  }
  const snapshot = readSnapshot();
  snapshot.health = { score: Number(match[1]), grade: match[2] };
  writeFileSync(snapshotPath, `${JSON.stringify(snapshot, null, 2)}\n`);
  return snapshot;
}

function gradeColor(grade: string): string {
  switch (grade[0]?.toUpperCase()) {
    case 'A':
      return 'brightgreen';
    case 'B':
      return 'green';
    case 'C':
      return 'yellow';
    case 'D':
      return 'orange';
    default:
      return 'red';
  }
}

// --- static collectors (committed sources only) -----------------------------
const BUILD_DIRS = new Set([
  'node_modules',
  '.output',
  'dist',
  '.nx',
  '.wxt',
  'coverage',
  '.turbo',
]);

function countWorkspaceMembers(): number {
  let count = 0;
  for (const group of ['apps', 'packages'] as const) {
    for (const entry of readdirSync(resolve(repoRoot, group), { withFileTypes: true })) {
      if (entry.isDirectory() && existsSync(resolve(repoRoot, group, entry.name, 'package.json'))) {
        count += 1;
      }
    }
  }
  return count;
}

function countTestFiles(): number {
  let count = 0;
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        if (!BUILD_DIRS.has(entry.name)) walk(resolve(dir, entry.name));
      } else if (/\.test\.tsx?$/.test(entry.name)) {
        count += 1;
      }
    }
  };
  for (const group of ['apps', 'packages'] as const) walk(resolve(repoRoot, group));
  return count;
}

function countExtensionPermissions(): number {
  const config = readFileSync(resolve(repoRoot, 'apps/extension/wxt.config.ts'), 'utf8');
  // `\b` does not break inside `host_permissions` / `data_collection_permissions`
  // (the `_` is a word char), so this matches only the standalone array.
  const match = /\bpermissions:\s*\[([^\]]*)\]/.exec(config);
  if (!match) {
    throw new Error(
      '[readme-metrics] could not find `permissions: [...]` in apps/extension/wxt.config.ts — ' +
        'update countExtensionPermissions() if the manifest moved.',
    );
  }
  return match[1]
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean).length;
}

async function countSiteRules(): Promise<number> {
  const rulesPath = resolve(repoRoot, 'packages/rules/src/index.ts');
  const mod = (await import(pathToFileURL(rulesPath).href)) as { rules?: unknown[] };
  if (!Array.isArray(mod.rules)) {
    throw new Error('[readme-metrics] packages/rules/src/index.ts did not export a `rules` array.');
  }
  return mod.rules.length;
}

function readLicense(): string {
  const license = readFileSync(resolve(repoRoot, 'LICENSE'), 'utf8');
  const match = /^(\S+) License/m.exec(license);
  if (!match) throw new Error('[readme-metrics] could not read the SPDX id from LICENSE.');
  return match[1];
}

async function collectMetrics(snapshot: Snapshot): Promise<Metric[]> {
  const metrics: Metric[] = [];
  if (snapshot.health) {
    const { score, grade } = snapshot.health;
    metrics.push({
      label: 'code health',
      message: `${score} (${grade})`,
      color: gradeColor(grade),
    });
  }
  metrics.push(
    { label: 'site rules', message: String(await countSiteRules()), color: 'blue' },
    { label: 'permissions', message: String(countExtensionPermissions()), color: 'brightgreen' },
    { label: 'tests', message: `${countTestFiles()} files`, color: 'blue' },
    { label: 'workspace', message: `${countWorkspaceMembers()} members`, color: 'blue' },
    { label: 'license', message: readLicense(), color: 'green' },
  );
  return metrics;
}

// --- render + splice --------------------------------------------------------
function renderBlock(metrics: Metric[]): string {
  const badges = metrics.map((m) => `![${m.label}: ${m.message}](${badgeUrl(m)})`).join('\n');
  return `${METRICS_START}\n\n${badges}\n\n${METRICS_END}`;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function spliceBlock(readme: string, block: string): string {
  if (readme.includes(METRICS_START) && readme.includes(METRICS_END)) {
    const existing = new RegExp(
      `${escapeRegExp(METRICS_START)}[\\s\\S]*?${escapeRegExp(METRICS_END)}`,
    );
    return readme.replace(existing, block);
  }
  // First run: anchor the block just below the tagline blockquote.
  const lines = readme.split('\n');
  const blockquote = lines.findIndex((line) => /^>\s+/.test(line));
  if (blockquote === -1) {
    throw new Error(
      '[readme-metrics] no `> ` tagline blockquote found in README.md to anchor the block.',
    );
  }
  lines.splice(blockquote + 1, 0, '', block);
  return lines.join('\n');
}

// --- main -------------------------------------------------------------------
const mode = process.argv.includes('--refresh')
  ? 'refresh'
  : process.argv.includes('--check')
    ? 'check'
    : 'write';

const snapshot = mode === 'refresh' ? refreshSnapshot() : readSnapshot();
const readme = readFileSync(readmePath, 'utf8');
const next = spliceBlock(readme, renderBlock(await collectMetrics(snapshot)));
const refreshed = mode === 'refresh' ? ' (snapshot refreshed)' : '';

if (mode === 'check') {
  if (next !== readme) {
    console.error('✗ README metrics block is stale. Run `pnpm gen:readme` and commit README.md.');
    process.exit(1);
  }
  console.log('✓ README metrics block is up to date.');
} else if (next !== readme) {
  writeFileSync(readmePath, next);
  console.log(`✓ Wrote README metrics block${refreshed}.`);
} else {
  console.log(`✓ README metrics block already current${refreshed}.`);
}
